name: Deploy AWS

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    name: Run Test
    run: echo TODO Criar Test

  build_and_publish_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: eltonarodrigues/test-fiap-ci
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          # TODO - nao usar apenas o latest
  deploy-eks:
    needs: [ terraform ]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.AWS_CLUSTER_NAME }}

    - name: Deploy Secrets
      run: echo "${{ secrets.K8S_SECRETS }}" > k8s/secrets.yaml
    - name: Deploy no Kubernetes
      run: |
        kubectl apply -f k8s/secrets.yaml
        kubectl apply -f k8s/db/db.svc.yaml
        kubectl apply -f k8s/db/db.pv.yaml
        kubectl apply -f k8s/db/db.pvc.yaml
        kubectl apply -f k8s/db/db.deployment.yaml
        kubectl apply -f k8s/api/api.deployment.yaml
        kubectl apply -f k8s/api/api.svc.yaml

    - name: Verificar Status do Deploy
      run: |
        kubectl get pods